[package]
name = "f1_data_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.1"
clap = { version = "4.1.8", features = ["derive"] }
parquet = "34.0.0"
